# Put the following in when we rubocop-rspec is fixed
# require:
# - rubocop-rspec

AllCops:
  Include:
    - Guardfile
    - config.ru
    - Rakefile
    - !ruby/regexp /.*\.rake/
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - '**/bower_components/**/*'
    - vendor/**/*
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Documentation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Metrics/AbcSize:
  Exclude:
    - db/migrate/*
    - db/seeds/clothing_item_seeders/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/*
    - db/seeds/clothing_item_seeders/*

Metrics/ClassLength:
  Exclude:
    - db/seeds/clothing_item_seeders/*

HasAndBelongsToMany:
  Enabled: false
