AllCops:
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - '**/bower_components/**/*'

Documentation:
  Enabled: false

TrailingComma:
  EnforcedStyleForMultiline: comma

Metrics/MethodLength:
  Exclude:
    - db/migrate/*
