AllCops:
  Exclude:
    - db/schema.rb
    - node_modules/**/*

Documentation:
  Enabled: false

TrailingComma:
  EnforcedStyleForMultiline: comma

Metrics/MethodLength:
  Exclude:
    - db/migrate/*
