sudo: false
language: ruby
rvm:
- 2.2.2
cache:
  bundler: true
  directories:
  - node_modules
before_install:
- npm install
before_script:
- bundle exec rake assets:precompile
- bundle exec rake db:create db:migrate
script:
- bundle exec travis lint --skip-completion-check
- bundle exec rubocop -D
- bundle exec rake jsxhint
- bundle exec rake jscs
- bundle exec rake
- bundle exec teaspoon
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: ERr28OXoNvokbiM9EccyPA2GDC2A0Jd6Z3YBXrFPW9FFd+IhTCG47T8ZBqEh+woMXfCsDSnrtgA6crlw4NauTED2lkabhjg/z44ggcOKQ6BVejJ+EyfDTM2SCNcsf+GxU5+kxB0o+KM9Qq7Usk3oOLwCJxCdOcekIl8f8nWgoCM=
  app:
    secure: PAbRJxrunbmYSs7z96peO3Azr5+GP5IOd0iE1RjXdPbG5Rr7oBNlVXqKQxJVEqbH8RTP8+N19i8luLBjrgFFtZrEsMfogyLTPxKxK2YG8c3eAEVuh/2ZLvLjV57dcLU/coJ4Hl4WpduWVnBoP6e7MtnwN9aA+Kwt+g1Ly10fAiU=
  run:
  - bundle exec rake db:migrate VERSION=0
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
  - restart
