language: ruby
cache: bundler
rvm:
  - 2.1.3
before_install:
  - npm install jshint
install:
  - bundle install
before_script:
  - rake db:create db:migrate
script:
  - rubocop -D
  - travis lint --skip-completion-check
  - bundle exec rake jshint
  - bundle exec rake
