sudo: false
language: ruby
rvm:
- 2.2.3
cache:
  bundler: true
  directories:
  - node_modules
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install
before_script:
- bundle exec rake assets:precompile
- bundle exec rake db:create db:migrate
script:
- bundle exec travis lint --skip-completion-check
- bundle exec rubocop -D
- bundle exec rake jsxhint
- bundle exec rake jscs
- bundle exec rake
- bundle exec teaspoon
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: lRt4F0kyXEdD8u/5FNy5UBWaXZTkUhMD9gdSmjGVonYs4OiWtCqGeUGwUuurQXINN3PuosjKXVkBylbdUimfD3mLETBt1c64dtRPjcvKDw8CCmDF0QJ82kqaCVEBh3Bf7QtGHloT5xrPNeHJ8mYHS7hA9oLp7CbiyOo4eC257fI=
  app:
    secure: PAbRJxrunbmYSs7z96peO3Azr5+GP5IOd0iE1RjXdPbG5Rr7oBNlVXqKQxJVEqbH8RTP8+N19i8luLBjrgFFtZrEsMfogyLTPxKxK2YG8c3eAEVuh/2ZLvLjV57dcLU/coJ4Hl4WpduWVnBoP6e7MtnwN9aA+Kwt+g1Ly10fAiU=
  run:
  - bundle exec rake db:migrate VERSION=0
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
  - restart
