language: ruby
rvm:
- 2.1.5
cache:
  bundler: true
  directories:
  - node_modules
  - vendor/assets/bower_components
install:
- bundle install
- npm install
before_script:
- RAILS_ENV=production bundle exec rake assets:precompile
- bundle exec spring rake db:create db:migrate
script:
- travis lint --skip-completion-check
- rubocop -D
- bundle exec spring rake jsxhint
- bundle exec spring rake jscs
- bundle exec spring rake
- bundle exec spring teaspoon --coverage ci
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: ERr28OXoNvokbiM9EccyPA2GDC2A0Jd6Z3YBXrFPW9FFd+IhTCG47T8ZBqEh+woMXfCsDSnrtgA6crlw4NauTED2lkabhjg/z44ggcOKQ6BVejJ+EyfDTM2SCNcsf+GxU5+kxB0o+KM9Qq7Usk3oOLwCJxCdOcekIl8f8nWgoCM=
  app:
    secure: PAbRJxrunbmYSs7z96peO3Azr5+GP5IOd0iE1RjXdPbG5Rr7oBNlVXqKQxJVEqbH8RTP8+N19i8luLBjrgFFtZrEsMfogyLTPxKxK2YG8c3eAEVuh/2ZLvLjV57dcLU/coJ4Hl4WpduWVnBoP6e7MtnwN9aA+Kwt+g1Ly10fAiU=
  run:
    - rake db:migrate VERSION=0
    - rake db:migrate
    - rake db:seed
env:
  global:
  - secure: Ai9VTYB0nuXyFXFbtNTlYgLs5/OXtGOeMHdFWH4hTP9teCOQwh5nZaEnl7YEBGr3ITUY/nWf1Cuygl7AWJFalxptft4iTwnkUqKZ5ITGUxUOh9b+O0zuxfHuUncofr/g3mwhvi5ObD3mtDFAdh1rT94oecZD5re33H84EC+Ua20=
  - secure: PMaNicbYOkvOw5Igll8k38QZbsVYF5WB1aW7oHN3njxej7/XI+9RL+Cq/zIR4yWaIMRvUPjTMJpYXCvpvyrYF4RP5VlfzIgTxbUnwZ7fTHx2R0lzsDHbvVvr95jqksFM0CxmtFmyye4J+6RmCqtOCRqACMZxE4QyPg1DMEE3A48=
