language: ruby
cache: bundler
rvm:
- 2.1.3
install:
- bundle install
- npm install
- bundle exec rake bower:install:deployment
before_script:
- rake db:create db:migrate
script:
- rubocop -D
- travis lint --skip-completion-check
- bundle exec rake jsxhint
- bundle exec rake jscs
- bundle exec rake
- RAILS_ENV=test bundle exec teaspoon --coverage ci
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: ERr28OXoNvokbiM9EccyPA2GDC2A0Jd6Z3YBXrFPW9FFd+IhTCG47T8ZBqEh+woMXfCsDSnrtgA6crlw4NauTED2lkabhjg/z44ggcOKQ6BVejJ+EyfDTM2SCNcsf+GxU5+kxB0o+KM9Qq7Usk3oOLwCJxCdOcekIl8f8nWgoCM=
  app:
    secure: cQAG9NMKsPdoHrcF4QMO7pj9nwvBEDWgVhGkk4k1fpepC9R868+k9FqjyyrBX7Ye5DxENL2itl8IhZ97axyREUxXTRG2B9ZVyq4090nPGbHbEOrF72hEQawAh60YNTQaqAIYNiyQzEvsx6rPDOX/5Abd3J7hGMVVW1q/aX/dN+k=
  run:
    - 'rake db:reset'
    - 'rake clear_cache'
