paths:
  backbone: 'backbone/backbone'
  react: 'react/react'
  'react.backbone': 'react.backbone/react.backbone'
  'react-router': 'react-router/dist/react-router'
  reqwest: 'reqwest/reqwest'
  underscore: 'underscore/underscore'
map:
  backbone:
    jquery: 'objects/jquery_fake'
  '*':
    'bower/backbone': 'backbone'
    'bower/react': 'react.backbone' # This loads react
    'bower/react_router': 'react-router'
    'bower/reqwest': 'reqwest'
    'bower/underscore': 'underscore'
