paths:
  backbone: 'backbone/backbone'
  moment: 'moment/moment'
  react: 'react/react'
  'react.backbone': 'react.backbone/react.backbone'
  'react-router': 'react-router/dist/react-router'
  'react-with-addons': 'react/react-with-addons'
  reqwest: 'reqwest/reqwest'
  underscore: 'underscore/underscore'
map:
  backbone:
    jquery: 'objects/jquery_fake'
  '*':
    'bower/backbone': 'backbone'
    'bower/moment': 'moment'
    'bower/react': 'react.backbone' # This loads react
    'bower/react_router': 'react-router'
    'bower/reqwest': 'reqwest'
    'bower/underscore': 'underscore'
# Add shim config to application.js (so that it is set even after js is
#   compiled + optimized)
